[package]
name = "moreops"
version = "0.2.0"
authors = ["Konstantin Stepanov <me@kstep.me>"]
license = "MIT"
description = "a set of simple useful additional methods"
repository = "https://github.com/kstep/moreops"
readme = "README.md"
