[package]
name = "moreops"
version = "0.4.1"
authors = ["Konstantin Stepanov <me@kstep.me>"]
license = "MIT/Apache-2.0"
description = "a set of simple useful additional methods"
repository = "https://github.com/kstep/moreops"
readme = "README.md"
